- hosts: 127.0.01
  become: true
  tasks:
  - name: Install apache httpd (state=present is optional)
    apt:
      name: apache2
      state: present
  - name: Install apache httpd (state=present is optional)
    systemd:
      state: started
      name: started
      enabled: true