- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: install nginx
    apt:
      name: nginx
      state: present
      update_cache: true
      # Install should fail if the update cache time is bigger than 1.
    register: nginx_cache_time
    #failed_when: cache_time.cache_update_time > 1

  - name: Copy nginx file over
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    register: nginx_config
    #failed_when: nginx_config.diff.after.path == nginx_config.diff.before.path

  - name: print information from copy nginx file over
    debug:
      msg: "{{ nginx_config }}"

  - name: Restart nginx if needed
    service:
      name: nginx
      state: restarted
    when: nginx_config.changed == true