- hosts: localhost
  connection: local
  become: true
  # Uninstall nginx
  tasks:
  - name: uninstall nginx
    apt:
      name: nginx
      state: absent
      update_cache: true  
      
  - name: "uninstall packages"
    apt:
      name: nginx
      state: absent
      autoremove: yes